name: NinjaLead.ai CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # Phase 1: Tests et analyse de qualité
  test:
    name: Tests et Qualité du Code
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ninjalead_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
    
    - name: Configuration Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-flask bandit safety black flake8
    
    - name: Tests de formatage avec Black
      run: black --check --diff .
    
    - name: Tests de style avec Flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Analyse de sécurité avec Bandit
      run: bandit -r . -f json -o bandit-report.json || true
    
    - name: Vérification des vulnérabilités avec Safety
      run: safety check --json --output safety-report.json || true
    
    - name: Tests unitaires avec couverture
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ninjalead_test
        SESSION_SECRET: test-secret-key
        TESTING: true
      run: |
        pytest tests/ -v --cov=. --cov-report=xml --cov-report=term-missing
    
    - name: Upload des rapports de couverture
      uses: codecov/codecov-action@v3
      if: success()
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  # Phase 2: Analyse de sécurité avancée
  security:
    name: Scan de Sécurité
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
    
    - name: Scan des secrets avec TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
    
    - name: Analyse des dépendances
      uses: github/dependency-review-action@v3
      if: github.event_name == 'pull_request'

  # Phase 3: Build et validation
  build:
    name: Build et Validation
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
    
    - name: Configuration Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Build de l'application
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -c "from app import app; print('Build successful')"
    
    - name: Tests d'intégration
      env:
        DATABASE_URL: sqlite:///test.db
        SESSION_SECRET: test-secret-key
        TESTING: true
      run: |
        python -c "
        from app import app, db
        with app.app_context():
            db.create_all()
            print('Database schema created successfully')
        "
    
    - name: Validation des endpoints critiques
      env:
        DATABASE_URL: sqlite:///test.db
        SESSION_SECRET: test-secret-key
      run: |
        python -c "
        from app import app
        with app.test_client() as client:
            # Test health check
            response = client.get('/health')
            assert response.status_code == 200, f'Health check failed: {response.status_code}'
            
            # Test main page
            response = client.get('/')
            assert response.status_code == 200, f'Main page failed: {response.status_code}'
            
            print('All critical endpoints validated successfully')
        "

  # Phase 4: Déploiement (uniquement sur main)
  deploy:
    name: Déploiement Production
    runs-on: ubuntu-latest
    needs: [test, security, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
    
    - name: Notification de déploiement (début)
      run: |
        echo "🚀 Début du déploiement en production..."
        echo "Commit: ${{ github.sha }}"
        echo "Auteur: ${{ github.actor }}"
    
    # Ici vous pouvez ajouter vos étapes de déploiement spécifiques
    # selon votre plateforme (Heroku, AWS, GCP, etc.)
    
    - name: Préparation des artifacts
      run: |
        # Créer un package de déploiement
        tar -czf ninjalead-${{ github.sha }}.tar.gz \
          --exclude='.git' \
          --exclude='tests' \
          --exclude='*.pyc' \
          --exclude='__pycache__' \
          .
    
    - name: Tests post-déploiement
      run: |
        echo "Exécution des tests post-déploiement..."
        # Ici vous pouvez ajouter des tests de smoke pour vérifier le déploiement
    
    - name: Notification de déploiement (succès)
      run: |
        echo "✅ Déploiement terminé avec succès!"
        echo "Version déployée: ${{ github.sha }}"

  # Phase 5: Monitoring et alertes
  monitoring:
    name: Configuration Monitoring
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Vérification de la santé de l'application
      run: |
        echo "Configuration des alertes de monitoring..."
        # Ici vous pouvez configurer des alertes Sentry, DataDog, etc.
    
    - name: Tests de charge légers
      run: |
        echo "Exécution des tests de charge..."
        # Tests basiques pour vérifier la réactivité

# Configuration des notifications
notifications:
  webhooks:
    # Webhook pour Slack/Discord/Teams (à configurer)
    - url: ${{ secrets.WEBHOOK_URL }}
      if: always()